### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type 'Microsoft.Azure.ServiceBus.Grpc.Settlement+SettlementClient' while attempting to activate 'Microsoft.Azure.Functions.Worker.ServiceBusMessageActionsConverter'

### ISSUE THREAD

**Issue by kmadof** [Azure/azure-functions-on-container-apps#87]
**Which trigger/binding are you using?**
ServiceBusTrigger

**Which language are you using?**
F#, dotnet 8

**Provide resource details**
I cannot expose it publicly. 

**Expected behavior**
I expected to be able to execute functions and use [settlement actions](https://azure.microsoft.com/en-us/updates/ga-service-bus-message-settlement-in-isolated-worker-model-for-net-azure-functions/)

**Actual behavior**
I got this exception
```
Result: Function 'ServiceBusMessageHandler', Invocation id 'e056854c-4afc-4985-8949-ef8ad2c32a10': An exception was thrown by the invocation.
Exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Azure.ServiceBus.Grpc.Settlement+SettlementClient' while attempting to activate 'Microsoft.Azure.Functions.Worker.ServiceBusMessageActionsConverter'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Azure.Functions.Worker.Converters.DefaultInputConverterProvider.GetOrCreateConverterInstance(Type converterType) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\Converter\DefaultInputConverterProvider.cs:line 74
   at Microsoft.Azure.Functions.Worker.Converters.DefaultInputConverterProvider.<GetOrCreateConverterInstance>b__8_0(String key, String converterTypeAssemblyQualifiedName) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\Converter\DefaultInputConverterProvider.cs:line 101
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Azure.Functions.Worker.Converters.DefaultInputConverterProvider.GetOrCreateConverterInstance(String converterTypeName) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\Converter\DefaultInputConverterProvider.cs:line 91
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.GetConverterFromContext(ConverterContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 131
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.ConvertAsync(ConverterContext converterContext) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 39
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.ConvertAsync(FunctionContext context, FunctionParameter parameter, IConverterContextFactory converterContextFactory, IInputConversionFeature inputConversionFeature, Object source) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 160
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 58
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 46
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
   at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 38
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 91
Stack:    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Azure.Functions.Worker.Converters.DefaultInputConverterProvider.GetOrCreateConverterInstance(Type converterType) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\Converter\DefaultInputConverterProvider.cs:line 74
   at Microsoft.Azure.Functions.Worker.Converters.DefaultInputConverterProvider.<GetOrCreateConverterInstance>b__8_0(String key, String converterTypeAssemblyQualifiedName) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\Converter\DefaultInputConverterProvider.cs:line 101
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.Azure.Functions.Worker.Converters.DefaultInputConverterProvider.GetOrCreateConverterInstance(String converterTypeName) in D:\a\_work\1\s\src\DotNetWorker.Core\Converters\Converter\DefaultInputConverterProvider.cs:line 91
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.GetConverterFromContext(ConverterContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 131
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultInputConversionFeature.ConvertAsync(ConverterContext converterContext) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultInputConversionFeature.cs:line 39
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.ConvertAsync(FunctionContext context, FunctionParameter parameter, IConverterContextFactory converterContextFactory, IInputConversionFeature inputConversionFeature, Object source) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 160
   at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 58
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 46
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
   at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /mnt/vss/_work/1/s/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 38
   at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 91 
```

**To Reproduce**
Run this function
```
namespace Tatra

open Azure.Messaging.ServiceBus
open Microsoft.Azure.Functions.Worker
open Microsoft.Extensions.Logging
open System.Threading.Tasks

type ServiceBusMessageHandler(loggerFactory: ILoggerFactory) =
    let logger = loggerFactory.CreateLogger<ServiceBusMessageHandler>()

    [<Function("ServiceBusMessageHandler")>]
    member this.Run([<ServiceBusTrigger("upper-case-2", Connection = "ServiceBusConnection")>] message: ServiceBusReceivedMessage,
        messageActions: ServiceBusMessageActions) : Task =
        
        logger.LogInformation($"F# ServiceBusMessageHandler function processed message: {message}")

        logger.LogInformation("Message ID: {id}", message.MessageId);
        logger.LogInformation("Message Body: {body}", message.Body);

        task {
            return! messageActions.CompleteMessageAsync(message);
        }
```

here are the used packages
```
		<PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.6" />
		<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.2" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.23.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.18.1" OutputItemType="Analyzer" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.3.2" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.22.0" />
```

**Additional context**
I guess, but maybe we are missing [this extension](https://github.com/Azure/azure-functions-dotnet-worker/blob/7b1bd29623ac71682356d12336eec88c99d92213/extensions/Worker.Extensions.ServiceBus/src/ServiceBusExtensionStartup.cs#L22)
```
// Copyright (c) Jacob Viau. All rights reserved.
// Licensed under the MIT. See LICENSE file in the project root for full license information.

using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Core;
using Microsoft.Azure.Functions.Worker.Extensions.Rpc;
using Microsoft.Azure.ServiceBus.Grpc;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

[assembly: WorkerExtensionStartup(typeof(ServiceBusExtensionStartup))]

namespace Microsoft.Azure.Functions.Worker
{
    public sealed class ServiceBusExtensionStartup : WorkerExtensionStartup
    {
        public override void Configure(IFunctionsWorkerApplicationBuilder applicationBuilder)
        {
            applicationBuilder.Services.AddTransient(sp =>
            {
                IOptions<FunctionsGrpcOptions> options = sp.GetRequiredService<IOptions<FunctionsGrpcOptions>>();
                return new Settlement.SettlementClient(options.Value.CallInvoker);
            });
            applicationBuilder.Services.AddWorkerRpc();
        }
    }
}
```

**Comment by kmadof** [comment]
My understanding is that ServiceBusExtensionStartup should be executed, right?

> https://github.com/Azure/azure-functions-dotnet-worker/issues/2505#issuecomment-2147883038

**Comment by vishal1997** [comment]
@kmadof thanks for logging the issue here, post our investigation we would need more details of the resource. Can you please raise Azure Support ticket with all the resource details.

**Comment by kmadof** [comment]
@vishal1997 I created a support ticket - TrackingID#2410240050001857

**Comment by kmadof** [comment]
This is the reason why it doesn't work - [WorkerExtensionStartupAttribute does not work for F# #1246](https://github.com/Azure/azure-functions-dotnet-worker/issues/1246)

**Comment by kmadof** [comment]
It works if I execute startup manually

```
    .ConfigureFunctionsWebApplication(fun builder -> 
        let startup = new ServiceBusExtensionStartup()
        startup.Configure(builder)
    )
```
However, knowing that a startup exists and needs to be executed is required.

**Comment by jviau** [comment]
This is expected behavior. The startup attribute relies on source generation which is not available to some environments (such as F#). Your workaround is correct: manually configure each extension.

Going to close this as there is it is external to us.
